---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yimt.
--- DateTime: 2020/12/11 上午10:12
---

enum = {}

---
--- 过滤
---
---@param source table @数据源
---@param cond function @过滤方法,cond(index, value)返回值true保留,false删除
---@return table
function enum.filter(source, cond)
    local new = {}

    for i, v in pairs(source) do
        if cond(i, v) then
            table.insert(new, v)
        end
    end

    return new
end

return enum