---
--- lua table模块加强tables
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yimt.
--- DateTime: 2020/12/11 下午4:40
---

tables = {}

---
--- 深拷贝
---
---@param source table @原始数据
---@return table @新数据
function tables.copy(source)
    if type(source) ~= 'table' then
        return source
    end

    local new = {}
    for k, v in pairs(source) do
        new[k] = tables.copy(v)
    end

    return new
end

return tables